services:
    doctrine_stats.data_collector.stats:
        class: steevanb\DoctrineStats\Bridge\Symfony3DoctrineStatsBundle\DataCollector\DoctrineStatsCollector
        arguments: [ '@doctrine.dbal.logger.profiling.default' ]
        public: false
        tags:
            -
                name: data_collector
                id: 'doctrine_stats'
                template: 'Symfony3DoctrineStatsBundle:DataCollector:template.html.twig'

    doctrine_stats.event_subscriber.doctrine:
        class: steevanb\DoctrineStats\Bridge\Symfony3DoctrineStatsBundle\EventSubscriber\DoctrineEventSubscriber
        arguments: [ '@doctrine_stats.data_collector.stats' ]
        tags:
            - { name: doctrine.event_subscriber }
            - { name: monolog.logger, channel: doctrine }

    doctrine_stats.event_listener.managed_entities:
        class: steevanb\DoctrineStats\Bridge\Symfony3DoctrineStatsBundle\EventListener\ManagedEntitiesListener
        arguments: [ '@doctrine', '@doctrine_stats.data_collector.stats' ]
        tags:
            - { name: kernel.event_listener, event: kernel.finish_request, method: saveManagedEntities }
