services:
    doctrine_stats.request_collector:
        class: steevanb\DoctrineStats\Bridge\Symfony3\DataCollector\DoctrineStatsCollector
        public: false
        tags:
            -
                name: data_collector
                id: 'doctrine_stats'
                template: 'DoctrineStatsBundle:DataCollector:template.html.twig'
            - { name: doctrine.event_listener, event: postLazyLoading }
